rimmyhub/jobposting-project

- src/company/company.controller.ts
- src/user/dto/create-user.dto.ts
- src/user/dto/update-user.dto.ts
- src/user/user.controller.ts
- src/user/user.service.ts
추가 내용:
유저DTO에 인수에 대한 타입을 상세 설정 및 에러처리 추가
유저삭제 및 전체조회는 추후 추가 예정
> Feat: 유저회원가입, 수정 상세조회

- src/domain/career.entity.ts
- src/domain/comment.entity.ts
- src/domain/company.entity.ts
- src/domain/resume.entity.ts
- src/domain/user.entity.ts
코멘트 - 경력
코멘트 - 유저
코멘트 -회사
이력서 - 유저
채팅 - 유저
관계설정 완료
> [feat] entity관계설정

- commons/http-exception.filter.ts
- src/auth/auth.controller.ts
- src/auth/auth.service.ts
- src/auth/user.guard.ts
- src/user/user.controller.ts
- src/user/user.service.ts
로그아웃
- 현재 클라이언트에서 보낸 req.cookies안에 authorization이 있는지 판단후 res.cookie로 authorization의 만료시간을 0으로 만들어 로그아웃 시킨다
회원탈퇴 (soft delete)
- 현재 로그인한 유저의  deleteAt컬럼의 값을 넣어주므로써 탈퇴했다고 판단
> [feat]  로그아웃, 유저회원탈퇴

- src/applicant/applicant.service.ts
- src/auth/auth.controller.ts
- src/auth/auth.module.ts
- src/auth/auth.service.ts
- src/auth/jwt/generate.token.ts
- src/auth/jwt/jwt.strategy.ts
- src/auth/jwt/refresh.token.ts
- src/company/company.service.ts
- src/domain/company.entity.ts
- src/domain/user.entity.ts
- src/user/user.service.ts
추가된 파일 
auth/refresh.token.ts
access토큰 재발급 API: /auth/refresh
access토큰이 만료가 되면 각 유저 혹은 회사에 저장되어 있는 crrRefreshToken의 만료일자를 확인하고 만료되지 않았다면 
새롭게 access토큰을 생성하고 클라이언트에게 보내준다.
> [feat] refresh token

- src/main.ts
- src/resume/dto/create-resume.dto.ts
- src/resume/resume.controller.ts
- src/resume/resume.module.ts
- src/resume/resume.service.ts
> feat : 이력서 관련 기능

- src/education/education.service.ts
> feat : 학력 예외처리 기능 추가

- src/main.ts
- src/user/dto/create-user.dto.ts
- src/user/user.controller.ts
- src/user/user.service.ts
> [fixed] dto 통일

- src/domain/resume.entity.ts
- src/resume/resume.service.ts
- src/utils/soft.delet.dto.ts
1. 이력서 생성 시 발생하는 userId err 수정해서 커밋합니다.
2. 소프트리무브 로직은 구현을 한 것 같긴한데 확인을 못해봤습니다.
1일 지난 데이터는 매일 자정 저절로 삭제되도록 해두었으니, 내일 내일모레 지나면서 삭제가 되는건지 확인해보도록 하겠습니다.
> feat : 이력서 error OK / softRemove TRY

- src/aboutme/aboutme.controller.ts
- src/applicant/applicant.controller.ts
- src/auth/auth.controller.ts
- src/career/career.controller.ts
- src/chat/chat.controller.ts
- src/comment/comment.controller.ts
- src/company/company.controller.ts
- src/education/education.controller.ts
- src/jobposting/jobposting.controller.ts
- src/portfolio/portfolio.controller.ts
- src/resume/resume.controller.ts
- src/user/user.controller.ts
> [feat] 서버의 API주소 앞에 /api추가

- views/jobposting.ejs
- views/public/css/jobposting.css
1. 최대한 와이어프레임과 비슷하게 구현을 하려고 했습니다.
2. 부트스트랩 사용했구요.
3. 수정할 부분 말씀주시면 수정하겠습니다.
> jobposting front

- src/portfolio/portfolio.controller.ts
- views/includes/header.ejs
- views/index.ejs
- views/public/css/container.css
- views/public/css/index.css
- views/public/css/signup.css
- views/signin.ejs
- views/signup.ejs
> [feat] 메인페이지 추가

- src/company/company.controller.ts
- src/company/company.service.ts
- src/company/dto/create-company.dto.ts
- src/main.ts
- src/upload/upload.module.ts
- views/includes/aboutme-add.ejs
- views/includes/career-add.ejs
- views/includes/career.ejs
- views/includes/education-add.ejs
- views/includes/education.ejs
- views/includes/portfolio-add.ejs
- views/includes/portfolio.ejs
- views/mypage-user.ejs
> fix : company singup

- src/app.controller.ts
- src/auth/auth.controller.ts
- src/auth/auth.service.ts
- src/auth/login.strategies/auth.strategy.ts
- src/company/company.controller.ts
- src/company/company.service.ts
- src/user/dto/create-user.dto.ts
- views/includes/header.ejs
- views/index.ejs
- views/public/css/signin.css
- views/public/js/signin.js
- views/public/js/signup.js
- views/signin.ejs
- views/signup.ejs
1. 메인페이지 css완성 
2. 로그인 페이지에서 회사 유저 로그인 가능
3. 회원가입 페이지에서 유저 회원가입 가능
! 오류: 회사 회원가입할 때 400에러가 뜸 추후 해결 예정
> [feat] 메인페이지 로그인 회원가입

- src/app.controller.ts
- views/jobposting.ejs
- views/mypage-user.ejs
- views/subpage-company.ejs
- views/subpage-user.ejs
1. 로그인이 필요한 페이지는 비로그인시 리다이렉트 처리
> [fixed] 헤더 에러 해결

- src/aboutme/aboutme.service.ts
- src/portfolio/portfolio.service.ts
- views/public/js/subpage-user.js
- views/subpage-user.ejs
1. resumeId window.location.search 로 받아와야 하는 부분 상의
(현재 API 자체가 형성이 안되어있음)
2. 자기소개서 포트폴리오 조회 로직이 잘못되어있어서 그것도 수정했습니다.
3. 유저 정보 fetch는 추가해야 합니다.
> subpage-user front / back connect SUCCESS test OK

- src/app.controller.ts
- src/domain/resume.entity.ts
- src/domain/user.entity.ts
- src/resume/resume.controller.ts
- src/resume/resume.service.ts
- src/user/user.controller.ts
- src/user/user.service.ts
- views/index.ejs
- views/public/js/index.js
1. 이력서 유저의 entity관계 수정
2. 데이터를 불러올때 createQueryBuilder를 이용하여 user테이블과 조인
3. 메인페이지에서 이력서를 전체조회 가능
> [feat] 메인페이지에서 이력서 조회

- src/domain/resume.entity.ts
- src/user/user.controller.ts
- views/public/js/index.js
- views/public/js/subpage-user.js
- views/subpage-user.ejs
1. 기존 하드코딩하던 resumeId / userId 이제 안하셔도 됩니다.
2. 코드에서 필요없는 주석 , console.log , 안쓰는 코드는 제외시켰습니다.
> subpage-user Complete test OK

- src/education/education.service.ts
1. 입력값 없이 생성되는 부분 예외처리 추가
2. 생성된 데이터가 없으면 에러 처리 하는 부분 추가
> education err complete

- src/events/events.gateway.ts
- src/upload/upload.module.ts
- views/includes/header.ejs
> [feat] 메세지창

- src/domain/resume.entity.ts
- src/education/education.service.ts
- src/resume/resume.controller.ts
- src/resume/resume.service.ts
- src/user/user.controller.ts
- src/user/user.service.ts
- views/includes/education-add.ejs
- views/includes/user.ejs
- views/mypage-user.ejs
- views/public/js/mypage-user.js
- views/public/js/subpage-user.js
- views/subpage-user.ejs
1. 유저 정보 수정 메서드가 PATCH -> PUT으로 수정되었습니다. 이유는 서버에서 body값을 가지고 fetch를 보낼 때 생기는 오류로 인해서 수정하였습니다.
2. subpage / mypage 아직 이력서가 존재하지 않거나, 학력이 존재하지 않을 경우 예외처리를 추가하였습니다.
3. education service 부분에서 예외처리를 몇가지 추가 및 수정 하였습니다.
> mypage / subpage-user / back-front CONNECTING / not yet ok

- views/includes/company.ejs
- views/includes/footer.ejs
- views/includes/jobposting-add.ejs
- views/includes/jobposting.ejs
- views/includes/review.ejs
- views/jobposting-company.ejs
- views/jobposting-user.ejs
- views/mypage-company.ejs
- views/mypage-user.ejs
- views/subpage-company.ejs
- views/subpage-user.ejs
> feat: css 추가

- commons/education.enums.ts
- src/aboutme/aboutme.controller.ts
- src/aboutme/aboutme.service.ts
- src/career/career.controller.ts
- src/career/career.service.ts
- src/domain/aboutme.entity.ts
- src/domain/career.entity.ts
- src/domain/portfolio.entity.ts
- src/education/education.controller.ts
- src/education/education.service.ts
- src/portfolio/portfolio.controller.ts
- src/portfolio/portfolio.service.ts
- src/resume/resume.service.ts
- src/user/user.controller.ts
- src/user/user.service.ts
- views/includes/aboutme-add.ejs
- views/includes/aboutme.ejs
- views/includes/career-add.ejs
- views/includes/career.ejs
- views/includes/education.ejs
- views/includes/portfolio-add.ejs
- views/includes/portfolio.ejs
- views/mypage-user.ejs
- views/public/js/mypage-user.js
1. 혜림님이 만들어주신 학력 그 모달 그거를 오늘 튜터님 오시면 여쭤본다는걸 까먹었다가 마지막 테스트 하면서 발견했네요....
2. 학력 추가 / 학력 수정 / 학력 삭제 는 아직 안되실거고 유저내용 수정 로직은 아직 userId를 받아올 URL이 없어서 구현 안되어있습니다.
3. 마이페이지는 위 말씀드린 4개 기능 말고는 전부 다 정상작동 확인했습니다.
4. 위 4개 기능 지금 merge 하고 바로 작업 들어갈게요 ~
> 마이페이지 기능구현 중 (학력 추가, 수정, 삭제 / 유저내용 수정)을 제외한 모든 기능 test OK

- src/app.controller.ts
- src/company/company.controller.ts
- src/company/company.service.ts
- src/jobposting/jobposting.controller.ts
- src/jobposting/jobposting.service.ts
- views/apply.ejs
- views/index.ejs
- views/public/css/apply.css
- views/public/js/apply.js
- views/public/js/index.js
jobposting, company 연결 및 더보기 버튼 기능 추가
> feat : front - main  jobposting, company, add button

- src/app.module.ts
- src/auth/auth.module.ts
- src/auth/jwt/jwt.user.guard.ts
- src/chat-content/chat-content.controller.spec.ts
- src/chat-content/chat-content.controller.ts
- src/chat-content/chat-content.module.ts
- src/chat-content/chat-content.service.spec.ts
- src/chat-content/chat-content.service.ts
- src/chat-content/dto/create-chat-content.dto.ts
- src/chat-content/dto/update-chat-content.dto.ts
- src/chat/chat.controller.ts
- src/chat/chat.geteway.ts
- src/chat/chat.module.ts
- src/chat/chat.service.ts
- src/company/company.controller.ts
- src/domain/chat.entity.ts
- src/domain/chatContent.entity.ts
- src/domain/education.entity.ts
- src/domain/resume.entity.ts
- src/domain/user.entity.ts
- src/user/user.controller.ts
- views/includes/header.ejs
- views/public/css/header.css
- views/public/js/header.js
> [feat] Chat content

- views/public/js/subpage-user.js
- views/subpage-user.ejs
1 유저로 로그인 시 유저서브페이지에서 메세지버튼 숨김
> Chat alarm

- src/auth/auth.service.ts
- src/chat/chat.controller.ts
- src/chat/chat.geteway.ts
- src/chat/chat.service.ts
- src/domain/chat.entity.ts
- src/user/user.controller.ts
- src/user/user.service.ts
- views/public/js/header.js
- views/public/js/subpage-user.js
1. 메시지버튼을 처음 눌렀을 때 바로 채팅창이 열릴수 있게 하기
2. 유저가 유저서브페이지에 들어갔을 때 메세지버튼이 안보이게 하기
> [feat] 메세지버튼

- jobposting;.sql
- src/chat-content/chat-content.service.ts
- src/chat/chat.controller.ts
- src/chat/chat.service.ts
- src/domain/chatContent.entity.ts
- views/includes/header.ejs
- views/index.ejs
- views/public/css/header.css
- views/public/css/index.css
- views/public/js/header.js
1. 메인페이지에 검색창 옮김
2. chatContent.entity에 isCheck를 추가
> Mainpage searchbox

- src/jobposting/jobposting.controller.ts
- src/jobposting/jobposting.service.ts
- src/user/user.controller.ts
- src/user/user.service.ts
- views/jobposting-user.ejs
- views/mypage-user.ejs
- views/public/js/jobposting-user.js
- views/public/js/mypage-user.js
- views/public/js/signup.js
> feat : front subpage jobposting

- src/chat-content/chat-content.controller.ts
- src/chat-content/chat-content.service.ts
- src/chat/chat.service.ts
- views/public/css/header.css
- views/public/js/header.js
1. 자신에게 온 새로운 메세지가 있으면 알람아이콘 표시
-----
개선해야할 점
1. 실시간 알람기능 
2. 새메세지의 메세지카드를 맨 위로 하기
> Check message

- package-lock.json
- package.json
- src/app.module.ts
- src/auth/jwt/jwt.company.guard.ts
- src/chat/chat.controller.ts
- src/chat/chat.geteway.ts
- views/public/js/header.js
- views/public/js/signin.js
1. cacheManager로 socket의 id를 임시저장
2. 메세지를 보내면 헤더의 메세지아이콘에 느낌표 채팅리스트안의 채팅카드에 느낌표가 생성
> [feat] Realtime alram

- src/jobcrawler/jobcrawler.service.ts
- src/jobposting/jobposting.controller.ts
- src/jobposting/jobposting.service.ts
- views/apply.ejs
- views/jobposting-add.ejs
- views/jobposting-edit.ejs
- views/public/js/apply.js
jobposting soft delete 구현 및 프론트 apply company영역에서 삭제된 채용공고 조회 가능
> feat : jobposting soft delete

- views/index.ejs
- views/public/js/index.js
> fix : main company image
